### ISSUE TITLE
Rigging Questions

### ISSUE THREAD

**Issue by ayatziv** [leapmotion/LeapUnrealModules#3]
hello Getnamo and many thanks for that ue4 sample project

kindly asking 2 questions:
1- When I run the costume rigging map - why the mannequin hands are very shaky while the low poly hands are stable? any solution for that?
2- at the same map - when I try to position the BSEchoHand near the VR pawn they disappear randomly ?

many thanks
amir

**Comment by getnamo** [comment]
1- As the current rigging is setup, it uses IK(Inverse Kinematics) to elbow and then FK(Forward Kinematics) for all child bones. Since elbow estimation is more uncertain this causes the shakiness. The example should be updated with a modified method where the IK of the elbow is set to wrist position + (elbow rotation * elbow length), that way when the FK is applied it will be correct for the estimated wrist position, which has higher accuracy. I've raised a separate issue for this here: https://github.com/leapmotion/LeapUnrealModules/issues/4

2- BSEcho hands are not a perfect rig for floating hands, and it is shown as a rigging example a single mesh type of rigging, but it still has some hiding logic as if it was a floating hand asset. Specifically, it is composed of a single asset for both hands as such it will hide when there is no tracking for both hands and re-appear when either is tracked. For the low poly hand there is a mesh per hand which hide independently based on whether it is being tracked. It is recommended to use one skeletal mesh per hand so that you can hide them independently, if you wish to make 'floating' hands.

**Comment by ayatziv** [comment]
Thanks!

So can you please advice what is the workflow to replace the low poly hands with another hands skeleton?

I have just purchased this hand skeleton:
https://www.unrealengine.com/marketplace/aaa-first-person-arms-pack


thanks again
amir
